/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.hyranasoftware.civsavefilelib.civ6;

/**
 *
 * @author danny_000
 */
public enum FullCivName {
    CIVILIZATION_AMERICA, CIVILIZATION_ARABIA, CIVILIZATION_AUSTRALIA, CIVILIZATION_AZTEC,
    CIVILIZATION_BRAZIL, CIVILIZATION_CHINA, CIVILIZATION_EGYPT, CIVILIZATION_ENGLAND, CIVILIZATION_FRANCE,
    CIVILIZATION_GERMANY, CIVILIZATION_GREECE, CIVILIZATION_INDIA, CIVILIZATION_JAPAN, CIVILIZATION_KONGO,
    CIVILIZATION_MACEDON, CIVILIZATION_NORWAY, CIVILIZATION_POLAND, CIVILIZATION_PERSIA, CIVILIZATION_ROME,
    CIVILIZATION_RUSSIA, CIVILIZATION_SCYTHIA, CIVILIZATION_SPAIN, CIVILIZATION_SUMERIA
}
